language: ruby
script: bundle exec rspec
deploy:
  provider: rubygems
  on:
    tags: true
  gem: ponto
  skip_cleanup: true
  api_key:
    secure: 17jdw6Oa2GbHKVLncFXo1eh/bFlJ3kdMOK2AWqPtlIDTpl/lWU8B5AfKysoOrDNWuiC/Qy7CeC0lhWbXAInbrh7A1QeNstWIZtccE3JA8YGV66JgnvOBhUG6NhdM9zu8/q6RyDiZ+oUnc6j4AlEu9zOFhd0sJMJRPQIOfwUyJgs2WTI1PZHT/iLuBU3twsL5JEWT8clCIlqxEQvjVp2GEAm8pDI5UO6bT0t2cQpBuTomGQfU02VwrWaDVa4IKTUclQFykgdHsU7sP6WE+mrep4wC4Nh32zuBFY6wy9e4VCmdoNuh+mGWB2hXT95Cf3N5JzEf2yRbXLL+VSdw90p/+u5uB6sofvO+Tg2Wy8ibukeuKug2ybd+V7JO1+DuZVuooq3i9diNAWIusYlScXe+0SiiWgBWewhjT6sJKsKlr6PgDceNuc7vrDkgvYGDn7YytnpA2yhOphOG9uqQtKBS5l4pDJSQ9gdnQ6s3GDY29+fcMta+z7sITDNN0kuSF6yzd/SLm6W6vy7oNjqDT+tHeDhXSA757xNGijT9DAAvtR1OQYNzW4EXgfkKJZGBMLA7jSPrLQp62klMKZAMgFlaCwPBzJahImJXdU1TW7RHGEKMGdklSuWyUo9XxBUxHFLTMlGCqqvXSpMi+cZvDs8zC3xSxXbBQd5ctyDGGVyiN4Y=
notifications:
  email: false
  slack:
    - rooms:
      - secure: Gnd8fTAuv30PF4GfUR9RVmEeJ9zyPJ+DS0LCuynDgnHZj8q3bV7TL7zGY39HNjn5C0GDhmVXy5ZbUj/VBo8wW69zrKTugqIzhu6FkVq7hOQIANkUWWqJ4bh13mX5LSS7F9klpBxMA9Q3dOPGSo1VTpJqGaCX1Jc0ffY4I2fK6IbdNAsoYV1/DQAjFAmzuqRYEmEfYO3brGvrhXHDtgfTVmNqRJIhYdstGmmIOhIC5zSgQrjXofxYtW+nZNifhW9KfknZJk2g2dwIZm271iJdx59JnDNB8nUGrPHBFMaux1Yc5TwQhamctYphNcnlBjztXvzIeOSmOZKekg0k06w1ySLYvJTkEpY+i2f7FU9VK2CTJR3SJwJN++iveQnispgEYUOxCdsXs7cGQPwsUymS7vw2h6qiHS1BFpyxpi1oP+g3ZagsA1CZOQcnagm0qyJ/A3twUGFG6p3PS9m3TrbIPN0aK0/t93jxKm8lbcC+OlpMJOMgMnajs86JU1s3I+8WDj3EKQzkg/zeZhzqyfW5BCvQxDgVLTca+WWNC+bLZLhDqvLrs23mNXFvKOKrt3j3hJjH0/JUxHImNMtInBCKxIpSOn8NiCUeiAl7O2vDRwqa0khbjc/nt0nJ6awf4ciqNMqCiUjX5NgLI4loTWU0V7mPANIa/eUCTTV5vmJHr3g=
      if: "(tag =~ ^v) AND (branch = master)"
    - rooms:
      - secure: Gnd8fTAuv30PF4GfUR9RVmEeJ9zyPJ+DS0LCuynDgnHZj8q3bV7TL7zGY39HNjn5C0GDhmVXy5ZbUj/VBo8wW69zrKTugqIzhu6FkVq7hOQIANkUWWqJ4bh13mX5LSS7F9klpBxMA9Q3dOPGSo1VTpJqGaCX1Jc0ffY4I2fK6IbdNAsoYV1/DQAjFAmzuqRYEmEfYO3brGvrhXHDtgfTVmNqRJIhYdstGmmIOhIC5zSgQrjXofxYtW+nZNifhW9KfknZJk2g2dwIZm271iJdx59JnDNB8nUGrPHBFMaux1Yc5TwQhamctYphNcnlBjztXvzIeOSmOZKekg0k06w1ySLYvJTkEpY+i2f7FU9VK2CTJR3SJwJN++iveQnispgEYUOxCdsXs7cGQPwsUymS7vw2h6qiHS1BFpyxpi1oP+g3ZagsA1CZOQcnagm0qyJ/A3twUGFG6p3PS9m3TrbIPN0aK0/t93jxKm8lbcC+OlpMJOMgMnajs86JU1s3I+8WDj3EKQzkg/zeZhzqyfW5BCvQxDgVLTca+WWNC+bLZLhDqvLrs23mNXFvKOKrt3j3hJjH0/JUxHImNMtInBCKxIpSOn8NiCUeiAl7O2vDRwqa0khbjc/nt0nJ6awf4ciqNMqCiUjX5NgLI4loTWU0V7mPANIa/eUCTTV5vmJHr3g=
      on_success: change
      on_failure: always
