language: ruby
script: bundle exec rspec
deploy:
  provider: rubygems
  on:
    tags: true
  gem: ponto
  skip_cleanup: true
  api_key:
    secure: 17jdw6Oa2GbHKVLncFXo1eh/bFlJ3kdMOK2AWqPtlIDTpl/lWU8B5AfKysoOrDNWuiC/Qy7CeC0lhWbXAInbrh7A1QeNstWIZtccE3JA8YGV66JgnvOBhUG6NhdM9zu8/q6RyDiZ+oUnc6j4AlEu9zOFhd0sJMJRPQIOfwUyJgs2WTI1PZHT/iLuBU3twsL5JEWT8clCIlqxEQvjVp2GEAm8pDI5UO6bT0t2cQpBuTomGQfU02VwrWaDVa4IKTUclQFykgdHsU7sP6WE+mrep4wC4Nh32zuBFY6wy9e4VCmdoNuh+mGWB2hXT95Cf3N5JzEf2yRbXLL+VSdw90p/+u5uB6sofvO+Tg2Wy8ibukeuKug2ybd+V7JO1+DuZVuooq3i9diNAWIusYlScXe+0SiiWgBWewhjT6sJKsKlr6PgDceNuc7vrDkgvYGDn7YytnpA2yhOphOG9uqQtKBS5l4pDJSQ9gdnQ6s3GDY29+fcMta+z7sITDNN0kuSF6yzd/SLm6W6vy7oNjqDT+tHeDhXSA757xNGijT9DAAvtR1OQYNzW4EXgfkKJZGBMLA7jSPrLQp62klMKZAMgFlaCwPBzJahImJXdU1TW7RHGEKMGdklSuWyUo9XxBUxHFLTMlGCqqvXSpMi+cZvDs8zC3xSxXbBQd5ctyDGGVyiN4Y=
notifications:
  email: false
  slack:
    - rooms:
      - secure: "pF1OBIgb263ZwZMFOMbjNNriZcfEh6rTucoOQzmicMWeFhlSV4n7X4g2bSF6Haer7zdpWQTfrJPQgsCLr7uCZuGp1uDPjJ1EZy1B1+DA5jPQBL+XuQGtdy9lEfyze+in2K4TcOWuzQoCMLQwN9YcUJunbQg3D56jFmejy0vyfdR2aj5DzZT+7AExhWFa7bB8ZgH6gcagQu2W1woJ6l8VJvuORARqIbufG7bxD/QHUGjLE/R/VktxcdoZge3stlrUpTaDG5MVccdrDxHX+y9ySP5lvKkwn9zgqUy9VSedYAdoMsRWGQuoeyxJYTGDd2/ErKIdOVX/dUCyA58ZQizOX1itE6pCtU6eYkXAHIMGjcbiUgptQsEiiKw4dWuMBjTTfekSaoIP3S7aPsZx86hOEj4N5ZBohXBzu+xDVetBm71L1VVKdvmzTxJwa7aM9Ty+CWOfS4klT2cGUTXcxKEVgwa+Ig2IHYF4+tOmzAx18l3L+yjO45fd8VpAvdnGzKFInvvNAYnq1R0j3BHo4dT6arxOC2Sedh3hI/8mU5OEXeTGWQgmYP4u7x9YsIRkoHwf7uZXsr2OJR6QjGV3a86rtwW9koVYN6XOwxClomK9v1mx1uLyOUDz9VLTmvCHS3bupyjkfOqC5iCNfLW2g8rNabGQAMNaychX8zLVUIom950="
      if: (tag =~ ^v) AND (branch = master)
    - rooms:
      - secure: "pF1OBIgb263ZwZMFOMbjNNriZcfEh6rTucoOQzmicMWeFhlSV4n7X4g2bSF6Haer7zdpWQTfrJPQgsCLr7uCZuGp1uDPjJ1EZy1B1+DA5jPQBL+XuQGtdy9lEfyze+in2K4TcOWuzQoCMLQwN9YcUJunbQg3D56jFmejy0vyfdR2aj5DzZT+7AExhWFa7bB8ZgH6gcagQu2W1woJ6l8VJvuORARqIbufG7bxD/QHUGjLE/R/VktxcdoZge3stlrUpTaDG5MVccdrDxHX+y9ySP5lvKkwn9zgqUy9VSedYAdoMsRWGQuoeyxJYTGDd2/ErKIdOVX/dUCyA58ZQizOX1itE6pCtU6eYkXAHIMGjcbiUgptQsEiiKw4dWuMBjTTfekSaoIP3S7aPsZx86hOEj4N5ZBohXBzu+xDVetBm71L1VVKdvmzTxJwa7aM9Ty+CWOfS4klT2cGUTXcxKEVgwa+Ig2IHYF4+tOmzAx18l3L+yjO45fd8VpAvdnGzKFInvvNAYnq1R0j3BHo4dT6arxOC2Sedh3hI/8mU5OEXeTGWQgmYP4u7x9YsIRkoHwf7uZXsr2OJR6QjGV3a86rtwW9koVYN6XOwxClomK9v1mx1uLyOUDz9VLTmvCHS3bupyjkfOqC5iCNfLW2g8rNabGQAMNaychX8zLVUIom950="
      on_success: change
      on_failure: always
